### ISSUE TITLE
RC Hangs on 'Complete' Save (RC 8.1.4)

### ISSUE THREAD

**Issue by jasonlones** [ctsit/linear_data_entry_workflow#26] opened 2018-03-12 22:01 UTC
In RC version 8.1.4, the LDEW external module hangs when saving any form as 'Complete'. Forms can be saved in other states (i.e. 'Incomplete', 'Unverified').

Other aspects of the modules seem to work as designed (e.g. ability to access forms is 'grayed out / hidden'). Issue discovered on initial install and testing of module.

**Comment by jkirby21** [comment] 2018-03-14 10:37
Just wanted to add, we are having the same issue while testing this module in 8.1.8.

**Comment by tbembersimeao** [comment] 2018-03-15 22:54
@jasonlones @jkirby21 thanks for the input! I'll look into this issue within the next days.

**Comment by tbembersimeao** [comment] 2018-03-19 15:41
@jasonlones @jkirby21 I'm having difficulties to reproduce this issue. Could you please provide further details about (like browser version, screenshots, etc)? Also, there is no REDCap version such as 8.1.4 or 8.1.8 available for download - the closest instance I could try was a 8.1.0 one.

Obs.: a procedure that can help me out is opening your browser console to view errors. You just need to follow [the instructions from this link](https://documentation.concrete5.org/tutorials/how-open-browser-console-view-errors), then reproduce the issue again, and finally check if any errors appear. Here is an example:

<img width="867" alt="browser console" src="https://user-images.githubusercontent.com/29384017/37605792-61292698-2b6a-11e8-9048-de9031b608d7.png">

**Comment by jasonlones** [comment] 2018-03-19 15:51
Try the LTS branch.  That is where you will find 8.1.4 and subsequent versions for 8.1.x.

Jason Lones
IT Analyst, Sr.
Duke Office of Clinical Research (DOCR)
School of Medicine
Phone: (919) 668-1787

**Comment by jasonlones** [comment] 2018-03-19 15:55
[cid:image002.jpg@01D3BF79.1DAD48C0]

Jason Lones
IT Analyst, Sr.
Duke Office of Clinical Research (DOCR)
School of Medicine
Phone: (919) 668-1787

**Comment by tbembersimeao** [comment] 2018-03-19 17:22
@jasonlones I installed REDCap 8.1.4 but I'm still not able to reproduce the issue. I did not get your last comment - did you try to attach an image?

**Comment by jasonlones** [comment] 2018-03-19 18:41
Yes.  Here is another attempt to attach.

Jason Lones
IT Analyst, Sr.
Duke Office of Clinical Research (DOCR)
School of Medicine
Phone: (919) 668-1787

**Comment by tbembersimeao** [comment] 2018-03-19 20:09
@jasonlones I'd try to attach the image to GitHub thread directly - it seems that replying the notification emails is not working.

**Comment by jasonlones** [comment] 2018-03-19 21:06
Okay.  Let's try this.

![capture](https://user-images.githubusercontent.com/22984358/37622349-c88d4b5c-2b97-11e8-800d-6a17dac26881.JPG)

**Comment by tbembersimeao** [comment] 2018-03-19 21:40
@jasonlones that helps a lot, thanks!

**Comment by tbembersimeao** [comment] 2018-03-19 22:26
@jasonlones thanks to your screenshot I was able to identify the cause of the problem, and a [pull request](https://github.com/ctsit/linear_data_entry_workflow/pull/27) is already created in order to fix it. We will let you know as soon as the next LDEW release is available. Thank you again!

**Comment by pbchase** [comment] 2018-03-29 13:40
Fixed by PR #27. Code release2 as version 2.1.2, and submitted to the REDCap repo.

**Closed by pbchase** 2018-03-29 13:40 UTC
Labels: bug
